// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "./src/config/data.config"
import { defineConfig } from "prisma/config";

export default defineConfig({

    schema: "prisma/schema.prisma",
    migrations: {
          seed: "npx tsx prisma/seed.js",

        path: "prisma/migrations",
    },
    datasource: {
        url: config.dbUrl,
    },
});